export const CHANGE_PAGE = 'CHANGE_PAGE';

export const PICK_GAME = 'PICK_GAME';
export const MAKE_RANDOM_PICKS = 'MAKE_RANDOM_PICKS';
export const CHANGE_BRACKET_PROPERTY = 'CHANGE_BRACKET_PROPERTY';
export const CLEAR_PICKS = 'CLEAR_PICKS';
export const PERFECT_PICKS = 'PERFECT_PICKS';
export const TOP_SEED_PICKS = 'TOP_SEED_PICKS';
export const BOTTOM_TEAM_PICKS = 'BOTTOM_TEAM_PICKS';

export const HIDE_SUBMIT_PICKS_DIALOG = 'HIDE_SUBMIT_PICKS_DIALOG';
export const SUBMIT_PICKS_TO_NETWORK = 'SUBMIT_PICKS_TO_NETWORK';
export const PICKS_SUBMISSION_FAILED = 'PICKS_SUBMISSION_FAILED';
export const PICKS_SUBMITTED_SUCCESSFULLY = 'PICKS_SUBMITTED_SUCCESSFULLY';

export const LOAD_ADMIN_METADATA = 'LOAD_ADMIN_METADATA';
export const SET_CONTRACT_METADATA = 'SET_CONTRACT_METADATA';
export const ADVANCE_CONTEST_STATE = 'ADVANCE_CONTEST_STATE';
export const SUBMIT_ORACLE_VOTE = 'SUBMIT_ORACLE_VOTE';
export const ADD_ORACLE = 'ADD_ORACLE';
export const CLAIM_TOP_ENTRY = 'CLAIM_TOP_ENTRY';
export const CLOSE_ORACLE_VOTING = 'CLOSE_ORACLE_VOTING';

export const LOAD_ENTRIES = 'LOAD_ENTRIES';
export const SET_ENTRIES = 'SET_ENTRIES';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
